### ISSUE TITLE
AttributeError: module 'orm' has no attribute 'ModelRegistry'

### ISSUE THREAD

**Issue by henshalb** [encode/orm#141]
## To replicate, 
```
from fastapi import FastAPI
import orm
import databases

app = FastAPI()

database = databases.Database("sqlite:///db.sqlite")
models = orm.ModelRegistry(database=database)


class Note(orm.Model):
    tablename = "notes"
    registry = models
    fields = {
        "id": orm.Integer(primary_key=True),
        "text": orm.String(max_length=100),
        "completed": orm.Boolean(default=False),
    }

@app.get("/")
async def index():
	await models.create_all()
	await Note.objects.create(text="Buy the groceries.", completed=False)
	note = await Note.objects.get(id=1)
	print(note)
	return {}
```

**Comment by aminalaee** [comment]
Thanks for reporting this, can you provide the stack trace and python/orm versions you use?

I can't reproduce this.

**Comment by henshalb** [comment]
```
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:     Started reloader process [57991] using statreload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/henshalb/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/home/henshalb/.local/lib/python3.8/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/henshalb/.local/lib/python3.8/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/home/henshalb/.local/lib/python3.8/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/henshalb/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/henshalb/Pictures/ds/app/./main.py", line 8, in <module>
    models = orm.ModelRegistry(database=database)
AttributeError: module 'orm' has no attribute 'ModelRegistry'
^CINFO:     Stopping reloader process [57991]
```

**Comment by henshalb** [comment]
```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/henshalb/.local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/home/henshalb/.local/lib/python3.8/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/henshalb/.local/lib/python3.8/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/home/henshalb/.local/lib/python3.8/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/henshalb/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/henshalb/Pictures/ds/app/./main.py", line 8, in <module>
    models = orm.ModelRegistry(database=database)
AttributeError: module 'orm' has no attribute 'ModelRegistry'
```

**Comment by aminalaee** [comment]
What version of `orm` are you using?

Have you created a module named `orm` in your project?

**Comment by henshalb** [comment]
```
(venv) henshalb@henshalb-IdeaPad-3-15IIL05:~/Pictures/ds/app$ which python/home/henshalb/Pictures/ds/venv/bin/python
(venv) henshalb@henshalb-IdeaPad-3-15IIL05:~/Pictures/ds/app$ pip show ormName: orm
Version: 0.3.1
Summary: An async ORM.
Home-page: https://github.com/encode/orm
Author: Tom Christie
Author-email: tom@tomchristie.com
License: BSD
Location: /home/henshalb/Pictures/ds/venv/lib/python3.7/site-packages
Requires: typesystem, databases
Required-by: 
(venv) henshalb@henshalb-IdeaPad-3-15IIL05:~/Pictures/ds/app$
```

**Comment by aminalaee** [comment]
> Have you accidentally created a module named `orm` in your project?

What about this?

**Comment by henshalb** [comment]
No

**Comment by henshalb** [comment]
![yes](https://user-images.githubusercontent.com/50692376/146755561-bc9151ff-a3d2-4386-8e3b-d49ecd05e0e0.png)

**Comment by aminalaee** [comment]
I think something's wrong with your setup. I don't think it's really related to the `orm`.

The uvicorn seems to be called outside of your env, maybe installed globally? And IDE python version is showing 3.7 but traceback is is showing python 3.8.

I think you need to check your setup.

**Comment by henshalb** [comment]
Okay, let me create a new one. Closing it.
