### ISSUE TITLE
NotNullViolationError: null value in column "id"

### ISSUE THREAD

**Issue by HarrySky** [encode/orm#21]
I just got an exception when tried to create new database entry via `await SomeModel.objects.create(...)`:

```
asyncpg.exceptions.NotNullViolationError: null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, John, Doe, a@b.c, 1997, M, null, f, null, f, 0, 0, null, 0, 0).
```

Model:
```
class SomeModel(Model):
    __tablename__ = DATABASE_TABLE
    __database__ = DATABASE
    __metadata__ = DATABASE_METADATA

    id = Integer(primary_key=True)
    # Some other fields
```

According to examples it should work without providing id field manually. Maybe I am missing something?

**Comment by tomchristie** [comment]
That's not intentional no. Didn't believe that to be the behavior. Does it replicate on SQLite as well?

**Comment by HarrySky** [comment]
It does not replicate on SQLite

**Comment by HarrySky** [comment]
Attaching traceback just in case:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/asynctest/case.py", line 297, in run
    self._run_test_method(testMethod)
  File "/usr/local/lib/python3.7/site-packages/asynctest/case.py", line 354, in _run_test_method
    self.loop.run_until_complete(result)
  File "/usr/local/lib/python3.7/site-packages/asynctest/case.py", line 224, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/builds/hashdivision/wgsystem/tests/registration_tests/test_schemas.py", line 38, in test_participant_registration
    participant = await register.register_participant()
  File "/builds/hashdivision/wgsystem/wg_system/registration/schemas.py", line 55, in register_participant
    info_channel=self.info_channel, expected_burpees=self.expected_burpees)
  File "/usr/local/lib/python3.7/site-packages/orm/models.py", line 208, in create
    instance.pk = await self.database.execute(expr)
  File "/usr/local/lib/python3.7/site-packages/databases/core.py", line 116, in execute
    return await connection.execute(query, values)
  File "/usr/local/lib/python3.7/site-packages/databases/core.py", line 198, in execute
    return await self._connection.execute(self._build_query(query, values))
  File "/usr/local/lib/python3.7/site-packages/databases/backends/postgres.py", line 151, in execute
    return await self._connection.fetchval(query, *args)
  File "/usr/local/lib/python3.7/site-packages/asyncpg/connection.py", line 439, in fetchval
    data = await self._execute(query, args, 1, timeout)
  File "/usr/local/lib/python3.7/site-packages/asyncpg/connection.py", line 1414, in _execute
    query, args, limit, timeout, return_status=return_status)
  File "/usr/local/lib/python3.7/site-packages/asyncpg/connection.py", line 1422, in __execute
    return await self._do_execute(query, executor, timeout)
  File "/usr/local/lib/python3.7/site-packages/asyncpg/connection.py", line 1444, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 196, in bind_execute
asyncpg.exceptions.NotNullViolationError: null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, John, Doe, a@b.c, 23, M, null, f, null, f, null, 0, null, 0, 0).
```

**Comment by HarrySky** [comment]
Files for quick replication (change URL to SQLite and it will work):

**./app/problematic.py**
```
from orm import Model, Integer, String
from databases import Database
from sqlalchemy import MetaData, create_engine

DATABASE = Database(url="postgresql:///app?user=app&host=postgres")
DATABASE_METADATA = MetaData()
DATABASE_ENGINE = create_engine(str(DATABASE.url))

class SomeModel(Model):
    __tablename__ = "random"
    __database__ = DATABASE
    __metadata__ = DATABASE_METADATA

    id = Integer(primary_key=True)
    name = String(max_length=64, allow_null=False)
```

**./tests/test_problematic.py**
```
import asynctest
from app.problematic import DATABASE, DATABASE_METADATA, DATABASE_ENGINE, SomeModel

class ProblematicTestCase(asynctest.TestCase):
    use_default_loop = True
    forbid_get_event_loop = False

    async def setUp(self):
        DATABASE_METADATA.create_all(DATABASE_ENGINE)
        await DATABASE.connect()

    async def tearDown(self):
        DATABASE_METADATA.drop_all(DATABASE_ENGINE)
        await DATABASE.disconnect()

    async def test_create(self):
        model = await SomeModel.objects.create(name="Random")
```

**./Dockerfile**
```
FROM python:3.7-alpine3.9

COPY requirements.txt /requirements.txt
RUN apk add --no-cache build-base postgresql-dev libpq \
    && pip3 install --no-cache-dir -r /requirements.txt
COPY app /workdir/app
COPY tests /workdir/tests
WORKDIR /workdir

CMD coverage run --source=app -m unittest discover -v -s tests/
```

**./requirements.txt**
```
databases[postgresql]
orm
asynctest
coverage
```

**./test** (bash script, run with sudo)
```
#!/bin/bash
set -e

docker stop postgres || true
docker rm postgres || true
docker network create test_problem || true

docker run --name=postgres \
    -e POSTGRES_DB=app \
    -e POSTGRES_USER=app \
    -e POSTGRES_PASSWORD="" \
    --network=test_problem \
    -d postgres:11-alpine

docker build -f Dockerfile -t test_problem:latest .
docker run --rm --network=test_problem test_problem:latest

docker stop postgres
docker rm postgres
```

Just run `sudo ./test` and it will fail as soon as you use PostgreSQL

**Comment by HarrySky** [comment]
I think it is better to use SQLite until this is not resolved. Let me know if I can help with this issue.

**Comment by tomchristie** [comment]
It looks to me like we have a test case which covers exactly this, and which works fine.
Anything I'm obviously missing?

https://github.com/encode/orm/blob/master/tests/test_models.py#L78

**Comment by tomchristie** [comment]
![Screen Shot 2019-04-12 at 14 30 08](https://user-images.githubusercontent.com/647359/56037416-8522b080-5d2f-11e9-9309-28d8a1a58cf9.png)

**Comment by HarrySky** [comment]
Yes, but I saw that you only test against SQLite

**Comment by andyjones11** [comment]
I've also just seen this issue. My setup is pretty much idential to what @HarrySky outlines above.

**Comment by EmadMokhtar** [comment]
I ran the test on my local machine.

## Steps

1. Modified the DATABASE_URL in 3 tests modules [`test_models`, `test_foreignkey`, and `test_column`].
2. Install `databases[postgresql]`.
3. Run `pytest`.

## Results

```
============================= test session starts ==============================
platform darwin -- Python 3.6.2, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
rootdir: /Users/emadmokhtar/github-emadmokhtar/orm
collected 12 items

tests/test_columns.py F                                                  [  8%]
tests/test_foreignkey.py FFFF                                            [ 41%]
tests/test_models.py ..FFFFF                                             [100%]

=================================== FAILURES ===================================
_______________________________ test_model_crud ________________________________

    @async_adapter
    async def test_model_crud():
        async with database:
>           await Example.objects.create()

tests/test_columns.py:59: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
orm/models.py:208: in create
    instance.pk = await self.database.execute(expr)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:116: in execute
    return await connection.execute(query, values)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:198: in execute
    return await self._connection.execute(self._build_query(query, values))
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/backends/postgres.py:151: in execute
    return await self._connection.fetchval(query, *args)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:439: in fetchval
    data = await self._execute(query, args, 1, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1414: in _execute
    query, args, limit, timeout, return_status=return_status)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1422: in __execute
    return await self._do_execute(query, executor, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1444: in _do_execute
    result = await executor(stmt, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   asyncpg.exceptions.NotNullViolationError: null value in column "id" violates not-null constraint
E   DETAIL:  Failing row contains (null, 2019-04-13 20:35:06.968808, 2019-04-13, 20:35:06.968832, , null, {}).

asyncpg/protocol/protocol.pyx:196: NotNullViolationError
_______________________________ test_model_crud ________________________________

    @async_adapter
    async def test_model_crud():
        async with database:
>           album = await Album.objects.create(name="Malibu")

tests/test_foreignkey.py:89: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
orm/models.py:208: in create
    instance.pk = await self.database.execute(expr)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:116: in execute
    return await connection.execute(query, values)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:198: in execute
    return await self._connection.execute(self._build_query(query, values))
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/backends/postgres.py:151: in execute
    return await self._connection.fetchval(query, *args)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:439: in fetchval
    data = await self._execute(query, args, 1, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1414: in _execute
    query, args, limit, timeout, return_status=return_status)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1422: in __execute
    return await self._do_execute(query, executor, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1444: in _do_execute
    result = await executor(stmt, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   asyncpg.exceptions.NotNullViolationError: null value in column "id" violates not-null constraint
E   DETAIL:  Failing row contains (null, Malibu).

asyncpg/protocol/protocol.pyx:196: NotNullViolationError
_____________________________ test_select_related ______________________________

    @async_adapter
    async def test_select_related():
        async with database:
>           album = await Album.objects.create(name="Malibu")

tests/test_foreignkey.py:104: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
orm/models.py:208: in create
    instance.pk = await self.database.execute(expr)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:116: in execute
    return await connection.execute(query, values)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:198: in execute
    return await self._connection.execute(self._build_query(query, values))
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/backends/postgres.py:151: in execute
    return await self._connection.fetchval(query, *args)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:439: in fetchval
    data = await self._execute(query, args, 1, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1414: in _execute
    query, args, limit, timeout, return_status=return_status)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1422: in __execute
    return await self._do_execute(query, executor, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1444: in _do_execute
    result = await executor(stmt, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   asyncpg.exceptions.NotNullViolationError: null value in column "id" violates not-null constraint
E   DETAIL:  Failing row contains (null, Malibu).

asyncpg/protocol/protocol.pyx:196: NotNullViolationError
________________________________ test_fk_filter ________________________________

    @async_adapter
    async def test_fk_filter():
        async with database:
>           malibu = await Album.objects.create(name="Malibu")

tests/test_foreignkey.py:124: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
orm/models.py:208: in create
    instance.pk = await self.database.execute(expr)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:116: in execute
    return await connection.execute(query, values)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:198: in execute
    return await self._connection.execute(self._build_query(query, values))
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/backends/postgres.py:151: in execute
    return await self._connection.fetchval(query, *args)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:439: in fetchval
    data = await self._execute(query, args, 1, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1414: in _execute
    query, args, limit, timeout, return_status=return_status)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1422: in __execute
    return await self._do_execute(query, executor, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1444: in _do_execute
    result = await executor(stmt, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   asyncpg.exceptions.NotNullViolationError: null value in column "id" violates not-null constraint
E   DETAIL:  Failing row contains (null, Malibu).

asyncpg/protocol/protocol.pyx:196: NotNullViolationError
_______________________________ test_multiple_fk _______________________________

    @async_adapter
    async def test_multiple_fk():
        async with database:
>           acme = await Organisation.objects.create(ident="ACME Ltd")

tests/test_foreignkey.py:158: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
orm/models.py:208: in create
    instance.pk = await self.database.execute(expr)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:116: in execute
    return await connection.execute(query, values)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:198: in execute
    return await self._connection.execute(self._build_query(query, values))
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/backends/postgres.py:151: in execute
    return await self._connection.fetchval(query, *args)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:439: in fetchval
    data = await self._execute(query, args, 1, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1414: in _execute
    query, args, limit, timeout, return_status=return_status)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1422: in __execute
    return await self._do_execute(query, executor, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1444: in _do_execute
    result = await executor(stmt, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   asyncpg.exceptions.NotNullViolationError: null value in column "id" violates not-null constraint
E   DETAIL:  Failing row contains (null, ACME Ltd).

asyncpg/protocol/protocol.pyx:196: NotNullViolationError
_______________________________ test_model_crud ________________________________

    @async_adapter
    async def test_model_crud():
        async with database:
            users = await User.objects.all()
            assert users == []
    
>           user = await User.objects.create(name="Tom")

tests/test_models.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
orm/models.py:208: in create
    instance.pk = await self.database.execute(expr)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:116: in execute
    return await connection.execute(query, values)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:198: in execute
    return await self._connection.execute(self._build_query(query, values))
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/backends/postgres.py:151: in execute
    return await self._connection.fetchval(query, *args)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:439: in fetchval
    data = await self._execute(query, args, 1, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1414: in _execute
    query, args, limit, timeout, return_status=return_status)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1422: in __execute
    return await self._do_execute(query, executor, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1444: in _do_execute
    result = await executor(stmt, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   asyncpg.exceptions.NotNullViolationError: null value in column "id" violates not-null constraint
E   DETAIL:  Failing row contains (null, Tom).

asyncpg/protocol/protocol.pyx:196: NotNullViolationError
________________________________ test_model_get ________________________________

    @async_adapter
    async def test_model_get():
        async with database:
            with pytest.raises(orm.NoMatch):
                await User.objects.get()
    
>           user = await User.objects.create(name="Tom")

tests/test_models.py:104: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
orm/models.py:208: in create
    instance.pk = await self.database.execute(expr)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:116: in execute
    return await connection.execute(query, values)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:198: in execute
    return await self._connection.execute(self._build_query(query, values))
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/backends/postgres.py:151: in execute
    return await self._connection.fetchval(query, *args)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:439: in fetchval
    data = await self._execute(query, args, 1, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1414: in _execute
    query, args, limit, timeout, return_status=return_status)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1422: in __execute
    return await self._do_execute(query, executor, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1444: in _do_execute
    result = await executor(stmt, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   asyncpg.exceptions.NotNullViolationError: null value in column "id" violates not-null constraint
E   DETAIL:  Failing row contains (null, Tom).

asyncpg/protocol/protocol.pyx:196: NotNullViolationError
______________________________ test_model_filter _______________________________

    @async_adapter
    async def test_model_filter():
        async with database:
>           await User.objects.create(name="Tom")

tests/test_models.py:116: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
orm/models.py:208: in create
    instance.pk = await self.database.execute(expr)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:116: in execute
    return await connection.execute(query, values)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:198: in execute
    return await self._connection.execute(self._build_query(query, values))
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/backends/postgres.py:151: in execute
    return await self._connection.fetchval(query, *args)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:439: in fetchval
    data = await self._execute(query, args, 1, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1414: in _execute
    query, args, limit, timeout, return_status=return_status)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1422: in __execute
    return await self._do_execute(query, executor, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1444: in _do_execute
    result = await executor(stmt, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   asyncpg.exceptions.NotNullViolationError: null value in column "id" violates not-null constraint
E   DETAIL:  Failing row contains (null, Tom).

asyncpg/protocol/protocol.pyx:196: NotNullViolationError
______________________________ test_model_exists _______________________________

    @async_adapter
    async def test_model_exists():
        async with database:
>           await User.objects.create(name="Tom")

tests/test_models.py:145: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
orm/models.py:208: in create
    instance.pk = await self.database.execute(expr)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:116: in execute
    return await connection.execute(query, values)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:198: in execute
    return await self._connection.execute(self._build_query(query, values))
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/backends/postgres.py:151: in execute
    return await self._connection.fetchval(query, *args)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:439: in fetchval
    data = await self._execute(query, args, 1, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1414: in _execute
    query, args, limit, timeout, return_status=return_status)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1422: in __execute
    return await self._do_execute(query, executor, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1444: in _do_execute
    result = await executor(stmt, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   asyncpg.exceptions.NotNullViolationError: null value in column "id" violates not-null constraint
E   DETAIL:  Failing row contains (null, Tom).

asyncpg/protocol/protocol.pyx:196: NotNullViolationError
_______________________________ test_model_count _______________________________

    @async_adapter
    async def test_model_count():
        async with database:
>           await User.objects.create(name="Tom")

tests/test_models.py:153: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
orm/models.py:208: in create
    instance.pk = await self.database.execute(expr)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:116: in execute
    return await connection.execute(query, values)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/core.py:198: in execute
    return await self._connection.execute(self._build_query(query, values))
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/databases/backends/postgres.py:151: in execute
    return await self._connection.fetchval(query, *args)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:439: in fetchval
    data = await self._execute(query, args, 1, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1414: in _execute
    query, args, limit, timeout, return_status=return_status)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1422: in __execute
    return await self._do_execute(query, executor, timeout)
../../.virtualenvs/encode-orm/lib/python3.6/site-packages/asyncpg/connection.py:1444: in _do_execute
    result = await executor(stmt, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   asyncpg.exceptions.NotNullViolationError: null value in column "id" violates not-null constraint
E   DETAIL:  Failing row contains (null, Tom).

asyncpg/protocol/protocol.pyx:196: NotNullViolationError
===================== 10 failed, 2 passed in 3.64 seconds ======================

```

**Comment by kcrebound** [comment]
same problem

**Comment by tomchristie** [comment]
Okay, can anyone who's seeing the issue move this forward by submitting a pull request that adds a (failing) test case for this?

**Comment by EmadMokhtar** [comment]
@tomchristie I can. Can we have sperate tests just for PostgreSQL? or shall we think about changing database engine via environment variable in CI?

**Comment by tomchristie** [comment]
Use `TEST_DATABASE_URLS` to set one or more database URLs.
We should ensure that the test runs across all configured engines in the same way as the existing test cases (so we can identify if it occurs in other cases, and confirm that any fix works correctly across all cases)

**Comment by kiddick** [comment]
same issue with postgres here

**Comment by kiddick** [comment]
That's not PR, but travis build with described issue and test set again postgres

**Comment by kiddick** [comment]
I've figured out the reason for that behavior. We are trying to execute insert statement with `NULL` value for primary key but that's not allowed in postgres
https://stackoverflow.com/questions/45290236/cannot-insert-null-as-primary-key-value-in-postgresql-for-flask-sqlalchemy-after

**Comment by tomchristie** [comment]
Okay - how do we ensure that the PK is properly setup as an auto-incrementing integer here?

**Comment by tomchristie** [comment]
Are we missing some option that needs to be set on the `Column` to do this correctly?

https://github.com/encode/orm/blob/master/orm/fields.py#L26

**Comment by gbozee** [comment]
One solution that appears to work is to ensure that if the id is `None`, it should be removed from the `kwargs` generated

https://github.com/encode/orm/blob/master/orm/models.py#L227

The following would resolve the issue at least for postgres.
```python
if not kwargs.get("id"):
        kwargs.pop("id", None)
expr = expr.values(**kwargs)
```
Also doesn't seem to pose any issues with sqlite.

**Comment by ramsrib** [comment]
i'm facing the same issue, is there any workarounds?

**Comment by sahil-b-shah** [comment]
Has this been resolved for Postgres? If not then why is the issue closed?

**Comment by HarrySky** [comment]
You are better off using maintained async ORM like ormar. This ORM does not seem to be maintained anymore
